# Generated by Django 3.2.8 on 2021-10-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_order_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='can_combine',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
